# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-04 10:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='id',
        ),
        migrations.AddField(
            model_name='document',
            name='article_id',
            field=models.IntegerField(default=-1, primary_key=True, serialize=False),
        ),
    ]
