# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-10 06:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0005_auto_20170308_0212'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wordindocument',
            name='tfidf',
        ),
    ]
