# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-04 12:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0002_auto_20170304_0343'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Question',
        ),
    ]
