# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-06 09:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0003_delete_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='city',
        ),
        migrations.RemoveField(
            model_name='document',
            name='country',
        ),
        migrations.RemoveField(
            model_name='document',
            name='language',
        ),
        migrations.RemoveField(
            model_name='document',
            name='province',
        ),
        migrations.RemoveField(
            model_name='document',
            name='wordCount',
        ),
        migrations.RemoveField(
            model_name='word',
            name='aoa',
        ),
        migrations.RemoveField(
            model_name='word',
            name='arousal',
        ),
        migrations.RemoveField(
            model_name='word',
            name='concreteness',
        ),
        migrations.RemoveField(
            model_name='word',
            name='corpusFrequency',
        ),
        migrations.RemoveField(
            model_name='word',
            name='dominance',
        ),
        migrations.RemoveField(
            model_name='word',
            name='idf',
        ),
        migrations.RemoveField(
            model_name='word',
            name='valence',
        ),
        migrations.RemoveField(
            model_name='wordindocument',
            name='documentFrequency',
        ),
        migrations.RemoveField(
            model_name='wordindocument',
            name='tf',
        ),
    ]
