# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-08 09:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0004_auto_20170306_0225'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='average_arousal',
        ),
        migrations.RemoveField(
            model_name='document',
            name='average_arousal_five_highest',
        ),
        migrations.RemoveField(
            model_name='document',
            name='average_valence',
        ),
        migrations.RemoveField(
            model_name='document',
            name='average_valence_five_highest',
        ),
    ]
